### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by BrandiBlitz** [MousePotatoDoesStuff/MCAfterStory#1]
1. I try to attempt to start the mod from the get-go, but it's broken. I had to carefully pick out anything that doesn't have to do with the base functionality of the mod and got it working.

![image](https://user-images.githubusercontent.com/101225938/165374405-b32b6192-a28a-4ab1-a1eb-68f9e5ae4d9c.jpeg)

2. If you make it to the option and exit, the game breaks.

**Comment by MousePotatoDoesStuff** [comment]
Issue fixed, thanks for the feedback!
